apiVersion: v1
kind: ResourceQuota
metadata:
  name: x
  namespace: default
spec:
  hard:
    services.nodeports: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: title
spec:
  selector:
    app: title
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
